# configuration file 

r : [0.2, 0.2, 0.1]
t : [-0.5, -0.5, -0.5]

voxel_size : 30000
move_to_origin : False

output_folder : 'data'

data_list : [
  [
    "/home/hci/Desktop/obrazky_prilohy/Pot/POHAN_P45395_A.ply", 
    "/home/hci/Desktop/obrazky_prilohy/Pot/POHAN_P45395_B.ply"
  ],
  # [
  #   "/path_to_breaking_bad_dataset/DrinkBottle/fractured_63/piece_0.obj",
  #   "/path_to_breaking_bad_dataset/DrinkBottle/fractured_63/piece_1.obj",
  # ]
]

